Add missing blank after STOP
The STOP statement requires preceding blank. Newer gcc
will fail with

     CASE DEFAULT; STOP'Err:WghtMtrx'
                      1
Error: Blank required in STOP statement near (1)

See:
https://bugs.gentoo.org/show_bug.cgi?id=604138

Signed-off-by: Justin Lecher <jlec@gentoo.org>